name: CI Linux
on:
  push:
    branches:
      - master
    paths:
      - 'Makefile'
      - '*.c'
      - 'tests/**'
      - '.github/workflows/ci-linux.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'Makefile'
      - '*.c'
      - 'tests/**'
      - '.github/workflows/ci-linux.yml'
  workflow_dispatch:
jobs:
  linux-build-and-run:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-26.04]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install build dependency
      run: sudo apt-get install -y libyubikey-dev
    - name: Build and test
      run: make test
